### ISSUE TITLE
Core Foundation

### ISSUE THREAD

**Issue by lowne** [luapower/objc#2]
How to use APIs that require CFStrings?
e.g.

``` lua
c.load'CoreFoundation'
c.load'ApplicationServices.HIServices'
c.AXUIElementCopyAttributeValue(sw,c.kAXFocusedUIElementAttribute,elm)

> bad argument #2 to 'func' (cannot convert 'string' to 'struct __CFString *')
```

I tried mucking around with `c.addfunction('AXUIElementCopyAttributeValue',{'^{__AXUIElement=}','@','^^v'},false)` but then the call appears to do nothing...

**Comment by capr** [comment]
Please use the forum for support questions, thank you!
